---
# tasks file for python
  - name: install python dependencies
    apt: name={{ item }} state=present force=yes
    with_items: 
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - python-mysqldb 
